### ISSUE TITLE
go get failed

### ISSUE THREAD

**Issue by snownd** [quickjs-go/quickjs-go#1]
An error has occurred when I tried to install quickjs on my machine.
As is shown：
![image](https://user-images.githubusercontent.com/30339830/104573717-2f133780-5690-11eb-9d75-b1043aa42824.png)

Go version: go1.1.5.6 linux/amd64 

OS: Ubuntu 18.04

**Comment by flyingtime** [comment]
> An error has occurred when I tried to install quickjs on my machine.
> As is shown：
> ![image](https://user-images.githubusercontent.com/30339830/104573717-2f133780-5690-11eb-9d75-b1043aa42824.png)
> 
> Go version: go1.1.5.6 linux/amd64
> 
> OS: Ubuntu 18.04

fixed
